### ISSUE TITLE
CMD Black box appears, then disappears and Server does not start

### ISSUE THREAD

**Issue by Donovan-Smith** [SIMRacingApps/SIMRacingApps#203]
First time downloading SRA, tried both signed and unsigned versions, got the CMD box poped up and disappeared. Used the command prompt to try to open it and this is the message I got: Desktop>SIMRacingAppsServer_1.9_Build_2019.04.12-signed.exe
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't obtain InputStream for com/sun/jna/win32-x86-64/jnidispatch.dll
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:962)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
        at com.sun.jna.Native.<clinit>(Native.java:190)
        at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
        at com.sun.jna.platform.win32.WinReg$HKEY.<init>(WinReg.java:42)
        at com.sun.jna.platform.win32.WinReg.<clinit>(WinReg.java:71)
        at com.SIMRacingApps.Util.FindFile.getUserDocumentsPath(FindFile.java:177)
        at com.SIMRacingApps.Util.FindFile.getUserPath(FindFile.java:193)
        at com.SIMRacingApps.Server.main(Server.java:644)

I cheked my java version and this is the result:
>java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

Any help would be appreciated, thanks

**Comment by jfgilliam** [comment]
Sounds like a bad download. Try downloading it again.
- Jeff Gilliam 

    On Thursday, May 16, 2019, 8:17:32 PM EDT, Donovan-Smith <notifications@github.com> wrote:  
 
 
First time downloading SRA, tried both signed and unsigned versions, got the CMD box poped up and disappeared. Used the command prompt to try to open it and this is the message I got: Desktop>SIMRacingAppsServer_1.9_Build_2019.04.12-signed.exe
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't obtain InputStream for com/sun/jna/win32-x86-64/jnidispatch.dll
at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:962)
at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
at com.sun.jna.Native.(Native.java:190)
at com.sun.jna.Pointer.(Pointer.java:54)
at com.sun.jna.platform.win32.WinReg$HKEY.(WinReg.java:42)
at com.sun.jna.platform.win32.WinReg.(WinReg.java:71)
at com.SIMRacingApps.Util.FindFile.getUserDocumentsPath(FindFile.java:177)
at com.SIMRacingApps.Util.FindFile.getUserPath(FindFile.java:193)
at com.SIMRacingApps.Server.main(Server.java:644)

I cheked my java version and this is the result:


java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)


Any help would be appreciated, thanks

**Comment by Donovan-Smith** [comment]
deleted downloaded application, emptied recycle bin, redownloaded and left destination folder as default (downloads folder) and same results:

Downloads>SIMRacingAppsServer_1.9_Build_2019.04.12-signed.exe
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't obtain InputStream for com/sun/jna/win32-x86-64/jnidispatch.dll
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:962)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
        at com.sun.jna.Native.<clinit>(Native.java:190)
        at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
        at com.sun.jna.platform.win32.WinReg$HKEY.<init>(WinReg.java:42)
        at com.sun.jna.platform.win32.WinReg.<clinit>(WinReg.java:71)
        at com.SIMRacingApps.Util.FindFile.getUserDocumentsPath(FindFile.java:177)
        at com.SIMRacingApps.Util.FindFile.getUserPath(FindFile.java:193)
        at com.SIMRacingApps.Server.main(Server.java:644)

current windows version is Microsoft Windows [Version 10.0.17134.765]
and current java: java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

Not sure what other information i need to provide but will be happy to assist

**Comment by jfgilliam** [comment]
I think I ran into this before a long time ago where a user had a local version of the jna library on their machine. It was put there by some other application. I have uploaded the 1.10 BETA version of SRA. Please download it from https://github.com/SIMRacingApps/SIMRacingApps/releases/tag/Version_1.10_Build_BETA-2019.05.18 and see if it works. I updated the jna library from 4.5 to 5.3. That's a big jump. If it doesn't work, look for that local copy. I also updated my Java to 1.8.0_212 for testing it.

**Comment by Donovan-Smith** [comment]
I had the same results with this version as well. I have no clue how to find the 'local copy'. I can follow directions well,  but i don't have a strong technical knowledge of this side of PCs. If you will guide me, I will follow! Thanks for all the support so far.

**Comment by jfgilliam** [comment]
My philosophy has been to not rely on the availability of external web sites to load libraries. To implement CORS, I have to list the sites in the headers. Instead put libraries, like React.js, as a local copy. Just put it in documents/simracingapps/external and load it from there. This has to be done as an App, not a widget. 

- Jeff

**Comment by jfgilliam** [comment]
So, I took a look in the .exe and the dll is there. I'm not really sure what the problem is.

![image](https://user-images.githubusercontent.com/5891428/58060792-106a3f80-7b41-11e9-9851-ddf068163b49.png)
