### ISSUE TITLE
API : /SIMRacingApps/Data/Car/ Error 500

### ISSUE THREAD

**Issue by bastienmp** [SIMRacingApps/SIMRacingApps#204]
Hey 

I m not sure this path is supposed to work, anyway it throws an error :
HTTP ERROR 500
Problem accessing /SIMRacingApps/Data/Car/. Reason:

    Server Error
Caused by:
com.owlike.genson.JsonBindingException: Could not deserialize to type interface java.util.Map
	at com.owlike.genson.Genson.deserialize(Genson.java:391)
	at com.owlike.genson.Genson.deserialize(Genson.java:306)
	at com.SIMRacingApps.servlets.Data.doGet(Data.java:411)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:864)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:133)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.owlike.genson.JsonBindingException: Could not deserialize to type interface java.util.Map
	at com.owlike.genson.Genson.deserialize(Genson.java:391)
	at com.owlike.genson.convert.DefaultConverters$UntypedConverterFactory$UntypedConverter.deserialize(DefaultConverters.java:1074)
	at com.owlike.genson.convert.NullConverter$NullConverterWrapper.deserialize(NullConverter.java:56)
	at com.owlike.genson.convert.DefaultConverters$MapConverter.deserialize(DefaultConverters.java:713)
	at com.owlike.genson.convert.DefaultConverters$MapConverter.deserialize(DefaultConverters.java:698)
	at com.owlike.genson.convert.NullConverter$NullConverterWrapper.deserialize(NullConverter.java:56)
	at com.owlike.genson.Genson.deserialize(Genson.java:389)
	... 33 more
Caused by: com.owlike.genson.JsonBindingException: Could not deserialize to type interface java.util.Map
	at com.owlike.genson.Genson.deserialize(Genson.java:391)
	at com.owlike.genson.convert.DefaultConverters$UntypedConverterFactory$UntypedConverter.deserialize(DefaultConverters.java:1074)
	at com.owlike.genson.convert.NullConverter$NullConverterWrapper.deserialize(NullConverter.java:56)
	at com.owlike.genson.convert.DefaultConverters$MapConverter.deserialize(DefaultConverters.java:713)
	at com.owlike.genson.convert.DefaultConverters$MapConverter.deserialize(DefaultConverters.java:698)
	at com.owlike.genson.convert.NullConverter$NullConverterWrapper.deserialize(NullConverter.java:56)
	at com.owlike.genson.Genson.deserialize(Genson.java:389)
	... 39 more
Caused by: com.owlike.genson.JsonBindingException: Could not deserialize to type interface java.util.Map
	at com.owlike.genson.Genson.deserialize(Genson.java:391)
	at com.owlike.genson.convert.DefaultConverters$UntypedConverterFactory$UntypedConverter.deserialize(DefaultConverters.java:1074)
	at com.owlike.genson.convert.NullConverter$NullConverterWrapper.deserialize(NullConverter.java:56)
	at com.owlike.genson.convert.DefaultConverters$MapConverter.deserialize(DefaultConverters.java:713)
	at com.owlike.genson.convert.DefaultConverters$MapConverter.deserialize(DefaultConverters.java:698)
	at com.owlike.genson.convert.NullConverter$NullConverterWrapper.deserialize(NullConverter.java:56)
	at com.owlike.genson.Genson.deserialize(Genson.java:389)
	... 45 more
Caused by: com.owlike.genson.stream.JsonStreamException: Illegal character around row 0 and column 975 awaited for literal (number, boolean or null) but read 'c'!
	at com.owlike.genson.stream.JsonStreamException$Builder.create(JsonStreamException.java:63)
	at com.owlike.genson.stream.JsonReader.consumeLiteral(JsonReader.java:524)
	at com.owlike.genson.stream.JsonReader.consumeValue(JsonReader.java:395)
	at com.owlike.genson.stream.JsonReader.next(JsonReader.java:379)
	at com.owlike.genson.convert.DefaultConverters$MapConverter.deserialize(DefaultConverters.java:712)
	at com.owlike.genson.convert.DefaultConverters$MapConverter.deserialize(DefaultConverters.java:698)
	at com.owlike.genson.convert.NullConverter$NullConverterWrapper.deserialize(NullConverter.java:56)
	at com.owlike.genson.Genson.deserialize(Genson.java:389)
	... 51 more

Thanks for the good work with SRA :)

**Comment by jfgilliam** [comment]
Ok, I see the problem. A couple of years back, I rewrote the Gauge class and never provided a serialized version of it. This will be fixed with the next BETA release.

**Comment by bastienmp** [comment]
The same error occure for /SIMRacingApps/Data/Car/ME/Gauge :)

**Comment by jfgilliam** [comment]
Thanks. I've been swamped with real work, but with the new build of iRacing coming out next week. I will be updating the content and releasing the BETA.
