### ISSUE TITLE
updating documentation for local builds

### ISSUE THREAD

**Issue by nullren** [SIMRacingApps/SIMRacingApps#222]
thanks for everything you've done so far. i was wanting to create some widgets but i'm noticing that it seems kind of hard to do so without rebuilding the entire project - so i tried to do that.

i noticed that some paths were hardcoded in `build.xml`, but i cloned all the repos into `${user.home}/Documents/`:
- SIMRacingApps
- SIMRacingAppsServer
- SIMRacingAppsWebContent
- SIMRacingAppsElectron
- SIMRacingApps.github.io
- SIMRacingAppsSIMPluginiRacing

then i tried building with `ant exe` (intellij, java 8), everything went through no problems. when running the created SIMRacingAppsServer.exe, i get a ton of NPEs. [here's a gist of the logs](https://gist.github.com/nullren/cebb4dd034de32324aee990ef89a8407).

what am i doing wrong? or are there extra steps required for the build? sorry for the questions.

**Comment by jfgilliam** [comment]
If you just want to work on widgets, you only need the SIMRacingAppsWebContent repository. Just put the widget you're working on in the Documents\SIMRacingApps\widget folder using the same path that's below that.

**Comment by nullren** [comment]
aha okay. i'll give that a try! but as for building the project, still kind of curious to get that working...

**Comment by nullren** [comment]
kind of similar to this one, in terms of developer docs https://github.com/SIMRacingApps/SIMRacingAppsServer/issues/1

**Comment by jfgilliam** [comment]
> kind of similar to this one, in terms of developer docs [SIMRacingApps/SIMRacingAppsServer#1](https://github.com/SIMRacingApps/SIMRacingAppsServer/issues/1) (which i wouldn't mind updating if i can get things to work 😅 )

That issue was related to creating a plugin where you can use the existing .exe as a jar and include it in the classpath.

As for the error in your log, see this post about compiling Jetty. Are you using the Jetty jars I include or your own. 

https://github.com/eclipse/jetty.project/issues/3244

**Comment by nullren** [comment]
from the gist:

> Looked at your log and that issue with the byte buffer I've seen before. Seems like it was a issue with using a new SDK than 1.8 to compile the code. Can't remember much more.

i'm running ant with `"C:\Program Files\Java\jdk1.8.0_241\bin\java.exe"`, so that should be okay...

> As for the error in your log, see this post about compiling Jetty. Are you using the Jetty jars I include or your own.

unless somewhere it's being downloaded, it should be using yours.

**Comment by nullren** [comment]
anyway, i'm much more familiar using maven or gradle for java builds, but i've also never worked on a project in windows. so in that regard, this is relatively new territory for me. not sure what the scope of this issue should be, but it would be nice to figure out what i need to do to get the build to work for me. hopefully that's okay with you if we keep it open until then? i don't want to get on your nerves 😅 

i may have been a little premature looking at the application logs since apparently still having trouble building. what version of node are you using for your build? i just installed node v14 since i had a failure in the `_javascriptdoc` target originally complaining about a missing node. now it complains something different:

```
cwd = C:\Users\renning\Documents\SIMRacingAppsWebContent
Server Version: 1.13_Build_BETA-2020.04.28
_javascriptdoc
Deleting directory C:\Users\renning\Documents\SIMRacingApps\JavaScriptDoc
Created dir: C:\Users\renning\Documents\SIMRacingApps\JavaScriptDoc
Running jsdoc
C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\requizzle\lib\requizzle.js:45
	if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
	               ^

TypeError: Cannot read property '0' of null
    at isNativeModule (C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\requizzle\lib\requizzle.js:45:17)
    at Requizzle.requizzle (C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\requizzle\lib\requizzle.js:82:6)
    at infectProxy (C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\requizzle\lib\loader.js:82:28)
    at Module.targetModule.require (C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\requizzle\lib\loader.js:101:11)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\jsdoc\lib\jsdoc\util\runtime.js:10:10)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Object.load (C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\requizzle\lib\loader.js:112:15)
Result: 1
```

**Comment by jfgilliam** [comment]
When I did this, I was very new at Java. Did not know about tools like Maven. I'm using Node v4.4.5. It's pretty old. Never really updated it. I have the mind set that once I find a tool that works, I don't update it until I need to. Having said that, Node is only used to generate the documentation from the .js files. It should not prevent you from building the .exe.
 I'm also using Eclipse and not IntelliJ. But, that shouldn't really matter because Ant is doing the build. But, Ant is built into Eclipse.
- Jeff 

    On Tuesday, April 28, 2020, 11:18:01 PM EDT, Renning Bruns <notifications@github.com> wrote:  
 
 


anyway, i'm much more familiar using maven or gradle for java builds, but i've also never worked on a project in windows. so in that regard, this is relatively new territory for me. not sure what the scope of this issue should be, but it would be nice to figure out what i need to do to get the build to work for me. hopefully that's okay with you if we keep it open until then? i don't want to get on your nerves 😅
 
i may have been a little premature looking at the application logs since apparently still having trouble building. what version of node are you using for your build? i just installed node v14 since i had a failure in the _javascriptdoc target originally complaining about a missing node. now it complains something different:
cwd = C:\Users\renning\Documents\SIMRacingAppsWebContent
Server Version: 1.13_Build_BETA-2020.04.28
_javascriptdoc
Deleting directory C:\Users\renning\Documents\SIMRacingApps\JavaScriptDoc
Created dir: C:\Users\renning\Documents\SIMRacingApps\JavaScriptDoc
Running jsdoc
C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\requizzle\lib\requizzle.js:45
	if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
	               ^

TypeError: Cannot read property '0' of null
    at isNativeModule (C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\requizzle\lib\requizzle.js:45:17)
    at Requizzle.requizzle (C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\requizzle\lib\requizzle.js:82:6)
    at infectProxy (C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\requizzle\lib\loader.js:82:28)
    at Module.targetModule.require (C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\requizzle\lib\loader.js:101:11)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\jsdoc\lib\jsdoc\util\runtime.js:10:10)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Object.load (C:\Users\renning\Documents\SIMRacingAppsWebContent\node_modules\angular-jsdoc\node_modules\requizzle\lib\loader.js:112:15)
Result: 1
